version: '3'

services:
  console:
    image: lvinkim/php-env-docker:latest
    volumes:
      - ".:/var/www/html"
    working_dir: /var/www/html
    entrypoint:
      - php
      - bin/console.php

  install:
    image: lvinkim/php-env-docker:latest
    volumes:
      - ".:/var/www/html"
    working_dir: /var/www/html
    command:
      - composer
      - install